# Generated by Django 4.1.3 on 2022-12-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imaga',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
