# Generated by Django 4.1.3 on 2022-12-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_post_imaga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imaga',
            new_name='image',
        ),
    ]
